'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {ArrowUpRight,ArrowRight,Check,ChevronRight,Send,Sparkles,ShieldCheck,Search,X,Trash2,Brain,FlaskConical,Settings2,BookOpen,RefreshCw,ChevronDown,Clock3} from 'lucide-react';
import {db,uid,type AgentRule,type ChatRecord,type AgentMemory} from '@/lib/db';
import {type Context,money,summary,bounds,localDate} from '@/lib/finance';
import {type FinanceState,type Finding,type ToolQuery,executeReadTool,localTransactionDraft,monthToDateComparison,contextSummary} from '@/lib/intelligence';
import {prepare,commit,type Pending,type Draft} from '@/lib/agent';
import Companion from './Companion';
import Simulation from './Simulation';
export type AgentSection='briefing'|'chat'|'simulation'|'memory';
type Props={context:Context;state:FinanceState;name:string;apiKey:string;model:string;rules:AgentRule[];findings:Finding[];initialSection:AgentSection;onSettings:()=>void;onInspect:(ids:string[],title:string)=>void;onNotify:(s:string)=>void;onDebts:()=>void};
const sections:[AgentSection,string,typeof Sparkles][]=[['briefing','Ringkasan',Sparkles],['chat','Obrolan',BookOpen],['simulation','Simulasi',FlaskConical],['memory','Memori',Brain]];
export default function AgentStudio({context,state,name,apiKey,model,rules,findings,initialSection,onSettings,onInspect,onNotify,onDebts}:Props){
 const [section,setSection]=useState<AgentSection>(initialSection),[input,setInput]=useState(''),[phase,setPhase]=useState<'idle'|'reading'|'analyzing'|'prepared'|'saving'|'verified'>('idle'),[trace,setTrace]=useState<string[]>([]),[pending,setPending]=useState<Pending|null>(null),[memoryDraft,setMemoryDraft]=useState(''),[newMemory,setNewMemory]=useState(''),[editMemory,setEditMemory]=useState<AgentMemory|null>(null),[lastVisit,setLastVisit]=useState(''),[error,setError]=useState(''),[usage,setUsage]=useState(0),[confirmClear,setConfirmClear]=useState(false);
 const chats=useLiveQuery(()=>db.chats.where('context').equals(context).sortBy('createdAt'),[context])||[];const memories=useLiveQuery(()=>db.memories.toArray(),[])||[];const events=useLiveQuery(()=>db.events.toArray(),[])||[];const abort=useRef<AbortController|null>(null),inFlight=useRef(false),generation=useRef(0),bottom=useRef<HTMLDivElement>(null);
 const busy=['reading','analyzing','saving'].includes(phase),liveFindings=findings.filter(f=>!events.find(e=>e.id===f.id)?.dismissed),all=summary(state.tx,state.capitals),balance=context==='personal'?all.personalBalance:all.businessBalance;
 useEffect(()=>{setSection(initialSection)},[initialSection]);
 useEffect(()=>{const key='finora-last-agent-'+context;setLastVisit(localStorage.getItem(key)||'');localStorage.setItem(key,new Date().toISOString());setPending(null);setMemoryDraft('');setError('');setPhase('idle');inFlight.current=false;generation.current++;abort.current?.abort();return()=>{generation.current++;abort.current?.abort()}},[context]);
 const changed=lastVisit?state.tx.filter(x=>x.context===context&&x.updatedAt>lastVisit).length:0;
 async function message(role:'user'|'agent',text:string,extras:Partial<ChatRecord>={}){await db.chats.add({id:uid(),context,role,text:text.slice(0,8000),createdAt:new Date().toISOString(),...extras});const history=await db.chats.where('context').equals(context).sortBy('createdAt');if(history.length>80)await db.chats.bulkDelete(history.slice(0,history.length-80).map(x=>x.id));}
 async function localReply(text:string,steps:string[],ids:string[]=[]){setTrace(steps);setPhase('analyzing');await message('agent',text,{source:'local',trace:steps,recordIds:ids});setPhase('verified')}
 async function ask(raw=input){const text=raw.trim();if(!text||inFlight.current||pending||memoryDraft)return;inFlight.current=true;setError('');setInput('');setSection('chat');setPhase('reading');setTrace(['Membaca konteks '+(context==='personal'?'Pribadi':'Bisnis')]);const id=++generation.current;abort.current=new AbortController();
 try{await message('user',text);
 if(/^ingat(?:lah)?\s*[:,-]?\s+/i.test(text)){const v=text.replace(/^ingat(?:lah)?\s*[:,-]?\s+/i,'').trim().slice(0,500);if(!v)throw Error('Tuliskan preferensi yang ingin diingat.');setMemoryDraft(v);setPhase('prepared');await message('agent','Aku siapkan memori ini. Kamu bisa memeriksanya sebelum menyimpan.',{source:'local'});return}
 const draft=localTransactionDraft(text,context,state.categories,rules);if(draft){setTrace(['Memahami satu transaksi','Memeriksa nominal dan kategori','Menghitung dampak saldo']);setPending(prepare([draft],state));setPhase('prepared');await message('agent',`Aku siapkan ${draft.description.toLowerCase()} sebesar ${money(draft.amount)}. Periksa tanggal dan kategorinya, ya.`,{source:'local'});return}
 if(/^cari\s+/i.test(text)){const q=text.replace(/^cari\s+/i,'').trim(),result=executeReadTool({name:'search',query:q,from:'1900-01-01',to:'9999-12-31'},state,context) as any;await localReply(result.count?`Ada ${result.count} catatan yang cocok dengan “${q}”. Total nominal ${money(result.total)}. ${result.count>40?'40 catatan terbaru ditampilkan.':''}`:`Belum ada catatan yang cocok dengan “${q}” di ${context==='personal'?'Pribadi':'Bisnis'}.`,['Menelusuri seluruh catatan konteks aktif','Menjumlahkan nominal yang cocok'],result.records.map((x:any)=>x.id));return}
 if(/bandingkan|banding\b|bulan lalu/i.test(text)&&!/catat|hapus|ubah/i.test(text)){const r=monthToDateComparison(),a:any=contextSummary(state,context,r.current),b:any=contextSummary(state,context,r.previous),v=context==='personal'?'expense':'profit',label=context==='personal'?'Pengeluaran':'Laba';await localReply(`${label} tanggal ${r.current.from}–${r.current.to}: ${money(a[v])}. Periode setara ${r.previous.from}–${r.previous.to}: ${money(b[v])}. Selisih ${money(a[v]-b[v])}. Perbandingan memakai jumlah hari yang sama.`,['Menetapkan periode yang sebanding','Menghitung kedua periode dari catatan'],state.tx.filter(x=>x.context===context&&((x.date>=r.previous.from&&x.date<=r.previous.to)||(x.date>=r.current.from&&x.date<=r.current.to))).map(x=>x.id));return}
 if(/kategori|pengeluaran terbesar/i.test(text)&&!/catat|hapus|ubah/i.test(text)){const r=executeReadTool({name:'categories'},state,context) as any;const g=[...r.groups].sort((a:any,b:any)=>b.amount-a.amount);await localReply(g.length?`Pengeluaran bulan berjalan:\n${g.map((x:any)=>`${x.name}: ${money(x.amount)}`).join('\n')}${context==='business'?'\nHPP penjualan terpisah dari kategori biaya ini.':''}`:'Belum ada pengeluaran bulan ini.', ['Mengelompokkan pengeluaran','Menjumlahkan tiap kategori'],g.flatMap((x:any)=>x.recordIds));return}
 if(/^(ringkas|ringkasan)|berapa.*saldo|^saldo\b|performa bisnis/i.test(text)){const s=summary(state.tx,state.capitals,monthToDateComparison().current);await localReply(context==='personal'?`Saldo pribadimu ${money(balance)}, ${name}. Bulan ini pemasukan ${money(s.income)}, pengeluaran ${money(s.expense)}, sehingga arus kas bersih ${money(s.net)}.`:`Saldo bisnis ${money(balance)}. Bulan ini omzet ${money(s.revenue)}, HPP ${money(s.hpp)}, biaya ${money(s.cost)}, dan laba bersih ${money(s.profit)}. Modal dihitung terpisah dari omzet.`,['Membaca catatan konteks aktif','Menghitung saldo dan periode berjalan'],[...state.tx.filter(x=>x.context===context).map(x=>x.id),...(context==='business'?state.capitals.map(x=>x.id):[])]);return}
 if(/^(halo|hai|hi|pagi|siang|sore|malam|elaina)[.!\s]*$/i.test(text)){await localReply(`Hai, ${name}. Aku di sini. Mau kita rapikan satu catatan, atau lihat rencana keuanganmu bersama?`,['Sapaan lokal']);return}
 if(/simulasi|bagaimana kalau|gimana kalau/i.test(text)){setSection('simulation');setPhase('idle');return}
 if(!apiKey){await localReply('Aku bisa merangkum, membandingkan, mencari catatan, dan menyiapkan transaksi sederhana tanpa koneksi. Untuk pertanyaan yang lebih bebas, sambungkan Gemini melalui Pengaturan AI.', ['Memeriksa kemampuan lokal']);return}
 if(!navigator.onLine)throw Error('Sedang offline. Ringkasan, pencarian, simulasi, dan catatan sederhana tetap tersedia.');
 setPhase('analyzing');setTrace(['Membaca konteks aktif','Meminta penjelasan Gemini']);const base={activeContext:context,today:localDate(),name,categories:state.categories.filter(c=>c.context===context&&!c.archived).map(({id,name,type,context})=>({id,name,type,context})),rules:rules.filter(r=>r.active&&r.context===context),memories:memories.filter(m=>m.context===context||m.context==='all').map(m=>m.text),snapshot:{balance,month:contextSummary(state,context,bounds('month'))},recentConversation:chats.slice(-6).map(({role,text})=>({role,text})),availableReadTools:['summary','categories','search','compare','debts']};
 const request=async(extra:object)=>{const res=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},signal:abort.current!.signal,body:JSON.stringify({key:apiKey,model,message:text,context:base,...extra})});const d=await res.json();if(!res.ok)throw Error(d.error||'Agent belum bisa merespons.');setUsage(n=>n+(d.usageTokens||0));return d};
 let data=await request({});const cloudSteps=['Membaca konteks aktif'];let evidence:string[]=[];
 if(data.tools?.length){const queries=(data.tools as ToolQuery[]).slice(0,3),results=queries.map(q=>({tool:q,result:executeReadTool(q,state,context)}));cloudSteps.push(...queries.map(q=>`Membaca data: ${q.name}`));evidence=results.flatMap(({result}:any)=>result.recordIds||result.records?.filter((x:any)=>x.categoryId).map((x:any)=>x.id)||result.groups?.flatMap((g:any)=>g.recordIds)||[]);setTrace([...cloudSteps,'Menyusun penjelasan dari hasil alat']);data=await request({toolResults:results,finalPass:true});if(data.tools?.length)throw Error('Batas pencarian Agent tercapai. Persempit pertanyaanmu.');}
 if(id!==generation.current)return;
 if((data.actions||[]).some((d:Draft)=>d.context!==context))throw Error('Rencana beda konteks. Pindahkan konteks terlebih dahulu.');
 if(data.actions?.length){setPending(prepare(data.actions,state));setPhase('prepared');cloudSteps.push('Memvalidasi rencana; menunggu konfirmasi')}else setPhase('verified');
 setTrace(cloudSteps);await message('agent',data.reply,{source:'gemini',trace:cloudSteps,recordIds:evidence});
 }catch(e){if((e as Error).name!=='AbortError'){setError(e instanceof Error?e.message:'Permintaan gagal.');setPhase('idle')}}finally{if(id===generation.current){inFlight.current=false;setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'}),50)}}}
 async function confirm(){if(!pending||inFlight.current)return;inFlight.current=true;setPhase('saving');setError('');try{const result=await commit(pending,state);setPending(null);setPhase('verified');setTrace(['Konfirmasi diterima','Validasi ulang data','Perubahan tersimpan','Saldo diverifikasi']);await message('agent',result,{source:'local',trace:['Disimpan setelah konfirmasi','Saldo diverifikasi ulang']});onNotify('Elaina: sudah tercatat. Satu langkah lebih teratur.')}catch(e){setError((e as Error).message);setPending(null);setPhase('idle')}finally{inFlight.current=false}}
 async function saveMemory(text:string,id?:string){const v=text.trim();if(!v||v.length>500)return;if(/AIza|api.?key|password|kata sandi/i.test(v)){setError('Simpan preferensi keuangan di memori; gunakan Pengaturan AI untuk kunci.');return}try{await db.memories.put({id:id||uid(),context,text:v,createdAt:editMemory?.createdAt||new Date().toISOString()});setMemoryDraft('');setNewMemory('');setEditMemory(null);setPhase('verified');onNotify('Memori Elaina disimpan.')}catch{setError('Memori belum tersimpan. Coba lagi.')}}
 const phaseLabel={idle:'Siap menemani',reading:'Membaca catatan',analyzing:'Memahami konteks',prepared:'Menunggu persetujuan',saving:'Menyimpan tindakan',verified:'Selesai diperiksa'}[phase];
 return <section className="studio"><div className="studio-header"><div className="studio-avatar"><img src="/art/elaina-avatar.webp" width="48" height="48" alt="Elaina"/><i/></div><div><b>Elaina</b><span>{phaseLabel} · {apiKey?'Gemini dikonfigurasi':'Mode lokal'}</span></div><button className="icon-button" onClick={onSettings} aria-label="Pengaturan AI"><Settings2 size={19}/></button></div><div className="studio-tabs" role="tablist" aria-label="Ruang Agent">{sections.map(([id,label,Icon])=><button key={id} role="tab" aria-selected={section===id} className={section===id?'selected':''} onClick={()=>setSection(id)}><Icon size={15}/>{label}</button>)}</div>
 {section==='briefing'&&<><div className="studio-briefing"><div><p className="world-kicker">A MOMENT WITH ELAINA</p><h2>Kita lihat bersama,<br/><em>{name}.</em></h2><p>{liveFindings.length?`Ada ${liveFindings.length} hal yang bisa kita perhatikan. Aku sudah menyiapkan catatan sumbernya.`:'Belum ada peringatan penting. Kamu bisa melihat ringkasan atau mencoba rencana baru.'}</p><button onClick={()=>ask('Ringkas keuangan bulan ini')} className="studio-start">Ringkas keuanganku <ArrowUpRight size={16}/></button></div><Companion className="studio-companion" mood="greeting" onTap={()=>ask('Halo')}/></div><div className="visit-line"><Clock3 size={14}/>{lastVisit?`${changed} catatan dibuat atau diperbarui sejak kunjungan Agent sebelumnya.`:'Ringkasan pertama perjalananmu bersama Elaina.'}</div><div className="findings-title"><h3>Yang perlu kamu lihat</h3><span>{liveFindings.length} temuan</span></div>{liveFindings.length?<div className="finding-list">{liveFindings.map(f=><article className={`finding priority-${f.priority}`} key={f.id}><span className="finding-mark">{f.type==='target'?'✦':f.type==='due'?'◷':'↗'}</span><div><h4>{f.title}</h4><p>{f.message}</p><div className="finding-actions">{f.type==='due'&&<button onClick={onDebts}>Buka utang/piutang <ArrowUpRight size={13}/></button>}{f.recordIds.length>0&&<button onClick={()=>onInspect(f.recordIds,f.title)}>Lihat {f.recordIds.length} catatan <ArrowUpRight size={13}/></button>}<details><summary>Cara dihitung</summary><p>{f.formula}</p></details></div></div><button className="icon-button" aria-label={`Tandai selesai ${f.title}`} onClick={()=>db.events.update(f.id,{dismissed:true,readAt:new Date().toISOString()})}><Check size={16}/></button></article>)}</div>:<div className="quiet-finding"><ShieldCheck size={23}/><p>Tidak ada temuan yang perlu dipaksakan.<span>Aku akan menyoroti kondisi yang memang berarti.</span></p></div>}<div className="agent-discover"><button onClick={()=>{setSection('simulation')}}><FlaskConical size={19}/><span>Bagaimana kalau?<small>Jelajahi kemungkinan sebelum memutuskan.</small></span><ArrowUpRight size={16}/></button><button onClick={()=>ask('Pengeluaran per kategori')}><Search size={19}/><span>Ke mana uangku pergi?<small>Telusuri kategori dan transaksi sumbernya.</small></span><ArrowUpRight size={16}/></button></div></>}
 {section==='simulation'&&<Simulation key={context} context={context} state={state}/>}
 {section==='memory'&&<div className="memory-space"><div className="memory-intro"><Brain size={27}/><h2>Hal kecil yang kuingat.</h2><p>Tambahkan preferensi yang ingin Elaina gunakan. Kamu menentukan apa yang diingat.</p></div><form onSubmit={e=>{e.preventDefault();saveMemory(editMemory?.text??newMemory,editMemory?.id)}}><label className="field">{editMemory?'Ubah memori':'Preferensi baru'}<textarea maxLength={500} placeholder="Contoh: bantu saya menabung untuk laptop; gunakan jawaban singkat." value={editMemory?.text??newMemory} onChange={e=>editMemory?setEditMemory({...editMemory,text:e.target.value}):setNewMemory(e.target.value)}/></label><div className="button-row"><button className="primary" disabled={!(editMemory?.text??newMemory).trim()}>Simpan memori</button>{editMemory&&<button className="secondary" type="button" onClick={()=>setEditMemory(null)}>Batal</button>}</div></form><div className="memory-list">{memories.filter(m=>m.context===context||m.context==='all').map(m=><article key={m.id}><span>✧</span><div><p>{m.text}</p><small>{m.context==='all'?'Semua konteks':m.context==='personal'?'Pribadi':'Bisnis'}</small></div><button className="text-action" onClick={()=>setEditMemory(m)}>Ubah</button><button className="icon-button" aria-label={`Hapus memori ${m.text}`} onClick={()=>db.memories.delete(m.id)}><Trash2 size={15}/></button></article>)}</div><p className="memory-privacy"><ShieldCheck size={14}/> Memori tersimpan lokal; yang sesuai konteks dikirim ketika kamu bertanya ke Gemini.</p></div>}
 {section==='chat'&&<div className="studio-chat"><div className="chat-toolbar"><span><i/>{apiKey?'Lokal + Gemini':'Lokal · tanpa kuota'}</span><button className="text-action" onClick={()=>setConfirmClear(true)} disabled={busy||!!pending||!!memoryDraft}>Bersihkan obrolan</button></div>{chats.length===0&&<div className="chat-welcome"><img src="/art/elaina-avatar.webp" alt="" width="72" height="72"/><h2>Aku mendengarkan.</h2><p>Ceritakan transaksimu, atau tanyakan sesuatu tentang catatanmu.</p></div>}<div className="studio-messages" aria-live="polite">{chats.slice(-40).map(c=><article className={`studio-message ${c.role}`} key={c.id}>{c.role==='agent'&&<img src="/art/elaina-avatar.webp" alt="" width="29" height="29"/>}<div><small>{c.role==='agent'?'ELAINA':'KAMU'}{c.source?` · ${c.source==='local'?'DI PERANGKAT':'GEMINI'}`:''}</small><p>{c.text}</p>{!!c.recordIds?.length&&<button className="evidence-button" onClick={()=>onInspect(c.recordIds!,'Catatan sumber jawaban')}>{c.recordIds.length} catatan sumber <ArrowUpRight size={13}/></button>}{!!c.trace?.length&&<details className="message-trace"><summary>Langkah yang dilakukan <ChevronDown size={12}/></summary>{c.trace.map((t,i)=><span key={i}><Check size={12}/>{t}</span>)}</details>}</div></article>)}{busy&&<div className="agent-working"><span className="working-orbit"/><div><b>{phaseLabel}…</b><small>{trace.at(-1)||'Menggunakan catatan yang relevan'}</small></div><button className="text-action" onClick={()=>{generation.current++;abort.current?.abort();inFlight.current=false;setPhase('idle')}} disabled={phase==='saving'}>Hentikan</button></div>}
 {pending&&<section className="plan-card"><p className="chapter-label">PREPARED / MENUNGGU KAMU</p><h3>Sudah kusiapkan.</h3>{pending.preview.map((p,i)=><p key={i} className="plan-item"><Check size={14}/>{p}</p>)}<div className="plan-fields">{pending.actions.map((d,i)=><small key={i}>{d.date||localDate()} · {d.context==='personal'?'Pribadi':'Bisnis'}{d.categoryId?' · '+state.categories.find(c=>c.id===d.categoryId)?.name:''}</small>)}</div><p className="plan-impact">{pending.expected}</p><div className="button-row"><button className="primary" onClick={confirm} disabled={busy}>Konfirmasi & simpan <Check size={15}/></button><button className="secondary" disabled={busy} onClick={()=>{setPending(null);setPhase('idle');message('agent','Rencana dibatalkan. Catatan keuanganmu tetap seperti sebelumnya.',{source:'local'})}}>Batalkan</button></div></section>}
 {memoryDraft&&<section className="plan-card"><p className="chapter-label">MEMORI BARU / BELUM DISIMPAN</p><h3>Boleh kuingat ini?</h3><p>{memoryDraft}</p><div className="button-row"><button className="primary" onClick={()=>saveMemory(memoryDraft)}>Simpan memori</button><button className="secondary" onClick={()=>{setMemoryDraft('');setPhase('idle')}}>Batal</button></div></section>}<div ref={bottom}/></div><div className="suggestion-rail">{['Ringkas bulan ini','Bandingkan bulan lalu','Catat beli makan 25 ribu'].map(t=><button key={t} disabled={busy||!!pending||!!memoryDraft} onClick={()=>ask(t)}>{t}<ArrowUpRight size={12}/></button>)}</div><form className="studio-composer" onSubmit={e=>{e.preventDefault();ask()}}><textarea id="agent-composer" rows={1} maxLength={2000} placeholder={pending?'Periksa rencana di atas dulu…':'Tanya Elaina atau ceritakan transaksimu…'} value={input} disabled={busy||!!pending||!!memoryDraft} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask()}}}/><button aria-label="Kirim pesan" disabled={!input.trim()||busy||!!pending||!!memoryDraft}><Send size={18}/></button></form><p className="studio-footer"><ShieldCheck size={12}/> Perubahan selalu menunggu persetujuanmu.{usage>0&&<span>{usage.toLocaleString('id-ID')} token pada sesi ini</span>}</p></div>}
 {error&&<p className="form-error studio-error" role="alert">{error}<button className="icon-button" aria-label="Tutup kesalahan" onClick={()=>setError('')}><X size={15}/></button></p>}
 {confirmClear&&<div className="modal-backdrop" onMouseDown={()=>setConfirmClear(false)}><section className="confirm-modal" role="dialog" aria-modal="true" aria-label="Bersihkan obrolan" onMouseDown={e=>e.stopPropagation()}><h2>Bersihkan obrolan?</h2><p>Hapus riwayat percakapan {context==='personal'?'Pribadi':'Bisnis'}. Catatan keuangan dan memori tetap tersimpan.</p><div className="button-row"><button className="secondary" onClick={()=>setConfirmClear(false)}>Batal</button><button className="danger-button" onClick={async()=>{await db.chats.where('context').equals(context).delete();setConfirmClear(false)}}>Hapus obrolan</button></div></section></div>}
 </section>
}
