'use client';
import {useEffect,useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {ArrowUpRight,ArrowDownLeft,ChevronRight,Plus,ArrowRight,Eye,EyeOff,ShieldCheck,ChevronDown,Sparkles,FlaskConical,Bookmark,X} from 'lucide-react';
import {type Context,type Transaction,type Capital,type Goal,type Limit,summary,bounds,previousBounds,dailySeries,money,shortMoney,monthKey,localDate} from '@/lib/finance';
import CategoryIcon from './CategoryIcon';
import Companion from './Companion';
import {type Preferences} from '@/lib/preferences';
import {type QuickTemplate} from '@/lib/db';
import {monthToDateComparison} from '@/lib/intelligence';
type Props={feedback?:string;preferences:Preferences;onPreferences:(p:Partial<Preferences>)=>void;templates:QuickTemplate[];onQuick:(t:QuickTemplate)=>void;onManageQuick:()=>void;onSimulation:()=>void;name:string;context:Context;tx:Transaction[];capitals:Capital[];goal?:Goal;limits:Limit[];catName:(id:string)=>string;insight:string[];onAdd:()=>void;onEdit:(row:Transaction)=>void;onCapital:()=>void;onTarget:()=>void;onContext:(c:Context)=>void;onNavigate:(tab:'transactions'|'calendar'|'reports'|'agent')=>void};
function RevealBalance({value,hidden}:{value:number;hidden:boolean}){const [shown,setShown]=useState(value);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.motion==='reduced'){setShown(value);return}let frame=0;const start=performance.now();const tick=(now:number)=>{const t=Math.min((now-start)/650,1);setShown(Math.round(value*(1-Math.pow(1-t,3))));if(t<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);return <>{hidden?'••••••••':money(shown)}</>}
export default function Dashboard({feedback,preferences,onPreferences,templates,onQuick,onManageQuick,onSimulation,name,context,tx,capitals,goal,limits,catName,insight,onAdd,onEdit,onCapital,onTarget,onContext,onNavigate}:Props){
 const hidden=preferences.hideBalance,setHidden=(hideBalance:boolean)=>onPreferences({hideBalance});
 const [greeting,setGreeting]=useState(''),[mood,setMood]=useState<'idle'|'greeting'|'success'>('idle');
 const hour=new Date().getHours(),salute=hour<11?'Selamat pagi':hour<15?'Selamat siang':hour<18?'Selamat sore':'Selamat malam';
 function greet(){setGreeting(`${salute}, ${name}. Aku di sini. Kita rapikan satu hal kecil hari ini?`);setMood('greeting')}
 useEffect(()=>{if(!preferences.greetings){setGreeting('');return}const timer=setTimeout(greet,650);return()=>clearTimeout(timer)},[context,preferences.greetings]);
 useEffect(()=>{if(feedback&&preferences.greetings){setGreeting('Sudah tercatat, '+name+'. Satu langkah kecil yang berarti. Terima kasih sudah meluangkan waktu.');setMood('success')}},[feedback]);
 useEffect(()=>{if(!greeting)return;const timer=setTimeout(()=>{setGreeting('');setMood('idle')},11000);return()=>clearTimeout(timer)},[greeting]);
 const month=bounds('month'),current=summary(tx,capitals,monthToDateComparison().current),all=summary(tx,capitals),previous=summary(tx,capitals,monthToDateComparison().previous);
 const isBusiness=context==='business',balance=isBusiness?all.businessBalance:all.personalBalance,income=isBusiness?current.revenue:current.income,outgoing=isBusiness?current.hpp+current.cost:current.expense,net=income-outgoing;
 const rows=tx.filter(x=>x.context===context),recent=[...rows].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)).slice(0,3);
 const graph=dailySeries(tx,capitals,context,{from:month.from,to:localDate()});
 const oldNet=isBusiness?previous.profit:previous.net;
 const totalLimit=limits.find(x=>!x.categoryId),target=isBusiness?(goal?.profitTarget||0):(totalLimit?.amount||0),achieved=isBusiness?current.profit:current.expense,progress=target?Math.max(0,Math.min(100,achieved/target*100)):0;
 const monthLabel=new Date().toLocaleDateString('id-ID',{month:'long',year:'numeric'});
 return <div className="celestial-dashboard">
 <section className="world-hero" aria-label="Ringkasan keuangan dan Elaina">
  <div className="world-environment" aria-hidden="true"/><div className="world-vignette" aria-hidden="true"/><div className="world-rays" aria-hidden="true"/><svg className="world-constellation" viewBox="0 0 480 260" aria-hidden="true"><path d="M50 175L140 80L230 130L330 42L418 93M230 130L310 211"/><g><circle cx="50" cy="175" r="2"/><circle cx="140" cy="80" r="3"/><circle cx="230" cy="130" r="2"/><circle cx="330" cy="42" r="3"/><circle cx="418" cy="93" r="2"/><circle cx="310" cy="211" r="2"/></g></svg><div className="celestial-dust" aria-hidden="true"><i/><i/><i/><i/><i/></div>
  <div className="world-heading"><div><p className="world-kicker">YOUR LITTLE FINANCIAL UNIVERSE</p><h1>{salute}, {name}.</h1><p className="world-date">{new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p></div><div className="world-context" aria-label="Konteks keuangan"><button className={!isBusiness?'selected':''} onClick={()=>onContext('personal')}>Pribadi</button><button className={isBusiness?'selected':''} onClick={()=>onContext('business')}>Bisnis</button></div></div>
  <div className="world-balance" key={context}><div className="balance-caption"><span>SALDO {isBusiness?'BISNIS':'PRIBADI'}</span><button onClick={()=>setHidden(!hidden)} aria-label={hidden?'Tampilkan saldo':'Sembunyikan saldo'}>{hidden?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><div className="world-number"><RevealBalance value={balance} hidden={hidden}/></div><p className="balance-annotation">Setiap langkah kecil, masa depan yang lebih tenang.</p><div className="world-flows"><div><span><ArrowDownLeft size={14}/>{isBusiness?'Omzet':'Pemasukan'}</span><b>{hidden?'••••••':money(income)}</b></div><div><span><ArrowUpRight size={14}/>{isBusiness?'HPP + biaya':'Pengeluaran'}</span><b>{hidden?'••••••':money(outgoing)}</b></div></div><small className="flows-period">Bulan ini · {monthLabel}</small><button className="hero-record" onClick={onAdd}><Plus size={18}/> Catat transaksi <ArrowUpRight size={17}/></button>{isBusiness&&<button className="hero-capital" onClick={onCapital}>Kelola modal <ChevronRight size={14}/></button>}</div>
  <Companion className="elaina-companion" mood={mood} onTap={greet}/>
  {greeting&&<div className="elaina-greeting" role="status"><span>ELAINA / UNTUKMU</span><button aria-label="Tutup sapaan" onClick={()=>{setGreeting('');setMood('idle')}}><X size={12}/></button><p>{greeting}</p><button className="greeting-cta" onClick={()=>onNavigate('agent')}>Temani aku <ArrowUpRight size={12}/></button></div>}
  <div className="companion-signature"><span>YOUR COMPANION</span><b>Elaina</b><i>✦</i></div>
  <div className="world-footer"><span><ShieldCheck size={13}/> Tersimpan di perangkatmu</span><button onClick={()=>document.getElementById('financial-pulse')?.scrollIntoView({behavior:'smooth'})}>Jelajahi keuanganmu <ChevronDown size={14}/></button></div>
 </section>
 <div className="home-content">
 <section className="quick-workbench" aria-label="Akses cepat"><div className="quick-heading"><span>BUAT HARI INI LEBIH RINGAN</span><button onClick={onManageQuick}>Atur pintasan <ArrowUpRight size={13}/></button></div><div className="quick-rail"><button className="quick-tool" onClick={onSimulation}><FlaskConical size={18}/><span>Bagaimana kalau?<small>Coba rencana keuangan</small></span><ArrowUpRight size={14}/></button><button className="quick-tool" onClick={()=>onNavigate('agent')}><Sparkles size={18}/><span>Temui Elaina<small>{insight.length?`${insight.length} temuan untukmu`:'Lihat cerita di balik angka'}</small></span><ArrowUpRight size={14}/></button>{templates.length?templates.slice(0,4).map(t=><button className="quick-template" key={t.id} onClick={()=>onQuick(t)}><CategoryIcon name={catName(t.categoryId)}/><span>{t.description}<small>{money(t.amount)}</small></span><Plus size={14}/></button>):<button className="quick-template" onClick={onManageQuick}><Bookmark size={18}/><span>Pintasan favorit<small>Ulangi transaksi sehari-hari</small></span><Plus size={14}/></button>}</div></section>
  <section className="financial-pulse" id="financial-pulse"><div className="editorial-heading"><div><p className="chapter-label">01 / FINANCIAL PULSE</p><h2>{isBusiness?'Dari omzet, menjadi laba.':'Ruang untuk tumbuh.'}</h2></div><button className="text-action" onClick={()=>onNavigate('reports')}>{monthLabel}<ArrowUpRight size={16}/></button></div>
  {isBusiness&&<div className="business-story">{[['Omzet',current.revenue],['HPP',current.hpp],['Biaya',current.cost],['Laba bersih',current.profit]].map(([label,value],i)=><div key={label}><span>{label}</span><b>{money(Number(value))}</b>{i<3&&<ArrowRight size={15}/>}</div>)}</div>}
  <div className="pulse-layout"><div className="pulse-summary"><span className="pulse-label">{isBusiness?'Laba bersih':'Arus kas bersih'} bulan ini</span><strong className={net<0?'negative-text':''}>{money(net)}</strong><p>{rows.length?(net>=0?'Pemasukanmu memberi ruang untuk langkah berikutnya.':'Pengeluaran melebihi pemasukan pada periode ini.'):'Mulai dengan satu catatan. Kita susun gambaran keuanganmu bersama.'}</p>{oldNet!==0&&<span className="pulse-comparison">{net-oldNet>=0?'+':''}{money(net-oldNet)} vs hari setara bulan lalu</span>}<button className="text-action" onClick={()=>onNavigate('reports')}>Lihat laporan <ArrowRight size={15}/></button></div>
  <div className="pulse-chart"><div className="pulse-chart-heading"><span>Perjalanan saldo</span><small>1–{new Date().getDate()} {new Date().toLocaleDateString('id-ID',{month:'short'})}</small></div>{rows.length?<ResponsiveContainer width="100%" height={176}><AreaChart data={graph} margin={{top:16,right:6,left:-17,bottom:0}}><defs><linearGradient id="lavenderArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9581bc" stopOpacity={.36}/><stop offset="100%" stopColor="#9581bc" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--line)" strokeDasharray="3 6"/><XAxis dataKey="date" tickFormatter={v=>String(Number(v.slice(8)))} axisLine={false} tickLine={false} minTickGap={35} tick={{fontSize:10,fill:'var(--muted)'}}/><YAxis tickFormatter={shortMoney} axisLine={false} tickLine={false} width={60} tick={{fontSize:10,fill:'var(--muted)'}}/><Tooltip formatter={v=>money(Number(v))} labelFormatter={v=>new Date(`${v}T12:00:00`).toLocaleDateString('id-ID',{day:'numeric',month:'short'})} contentStyle={{background:'var(--surface)',border:'1px solid var(--line)',borderRadius:10}}/><Area type="monotone" dataKey="balance" name="Saldo" stroke="#927cb4" strokeWidth={2.5} fill="url(#lavenderArea)" isAnimationActive={false}/></AreaChart></ResponsiveContainer>:<div className="pulse-empty"><span>✧</span><p>Perjalananmu dimulai di sini.</p><small>Grafik akan muncul setelah transaksi pertama.</small></div>}</div></div>
  </section>
  <div className="home-lower"><section className="journey-panel"><div className="editorial-heading"><div><p className="chapter-label">02 / A LITTLE CLOSER</p><h2>{isBusiness?'Tujuan bulan ini':'Jaga ritmemu.'}</h2></div><img src="/art/star-ornament.webp" width="36" height="44" alt="" loading="lazy"/></div><p>{isBusiness?'Satu penjualan lagi, satu langkah lebih dekat.':'Beri ruang untuk kebutuhan dan hal yang kamu sukai.'}</p><div className="journey-values"><span>{isBusiness?'Target laba':'Batas pengeluaran'}</span><b>{target?`${Math.round(progress)}%`:'Belum diatur'}</b></div><div className="journey-track"><i style={{width:`${progress}%`}}/></div><div className="journey-detail"><span>{money(achieved)}</span><span>{target?`dari ${money(target)}`:'bulan ini'}</span></div><button className="text-action" onClick={onTarget}>{target?'Sesuaikan tujuan':'Atur tujuanmu'} <ArrowRight size={14}/></button>{isBusiness&&all.capital>0&&<p className="capital-recovery">{Math.round(all.profit/all.capital*100)}% modal kembali · laba kumulatif / modal disetor</p>}</section>
  <section className="elaina-note"><div className="note-identity"><img src="/art/elaina-avatar.webp" width="46" height="46" alt="Elaina" loading="lazy"/><div><b>Sebuah catatan dari Elaina</b><span>FINORA AGENT</span></div><span className="note-star">✧</span></div><p>{insight[0]||(rows.length?'Catatanmu sudah tersusun. Mau kita lihat perjalanan keuangan bulan ini bersama?':'“Tidak perlu terburu-buru. Catat satu hal hari ini, dan biarkan perjalananmu dimulai.”')}</p><button onClick={()=>onNavigate('agent')}>Temui Elaina <ArrowUpRight size={17}/></button></section></div>
  <section className="recent-journal"><div className="editorial-heading"><div><p className="chapter-label">03 / YOUR DAILY JOURNAL</p><h2>Jejak terakhir.</h2></div><button className="text-action" onClick={()=>onNavigate('transactions')}>Semua transaksi <ChevronRight size={15}/></button></div>{recent.length?<div>{recent.map(row=><button key={row.id} className="journal-row" onClick={()=>onEdit(row)}><CategoryIcon name={catName(row.categoryId)}/><span><b>{row.description}</b><small>{catName(row.categoryId)} · {new Date(`${row.date}T12:00:00`).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</small></span><strong className={row.type==='income'?'positive-text':'negative-text'}>{row.type==='income'?'+':'−'}{money(row.amount)}</strong><ChevronRight size={15}/></button>)}</div>:<button className="journal-empty" onClick={onAdd}><Plus size={21}/><span>Halaman pertama masih kosong.<small>Catat transaksi pertamamu.</small></span><ArrowUpRight size={18}/></button>}</section>
  <footer className="home-end"><span>✦</span> Sedikit lebih teratur. Sedikit lebih tenang.</footer>
 </div></div>
}
