'use client';
import {useState} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {ArrowUpRight,FlaskConical,RotateCcw} from 'lucide-react';
import {type Context,summary,bounds,money,shortMoney} from '@/lib/finance';
import {simulate,type FinanceState} from '@/lib/intelligence';
export default function Simulation({context,state}:{context:Context;state:FinanceState}){
 const s=summary(state.tx,state.capitals,bounds('month')),all=summary(state.tx,state.capitals),biz=context==='business';
 const [income,setIncome]=useState(String(biz?s.revenue:s.income)),[expense,setExpense]=useState(String(biz?s.cost:s.expense)),[hpp,setHpp]=useState(String(s.hpp)),[revenueChange,setRevenue]=useState(20),[expenseChange,setExpenseChange]=useState(-10),[months,setMonths]=useState(3),[hppMode,setHppMode]=useState<'ratio'|'fixed'>('ratio');
 const calc=simulate({context,income:Number(income),expense:Number(expense),hpp:Number(hpp),revenueChange,expenseChange,hppMode,months,balance:biz?all.businessBalance:all.personalBalance});
 return <section className="scenario-studio"><div className="scenario-intro"><span className="scenario-icon"><FlaskConical size={23}/></span><div><p className="chapter-label">WHAT IF / RUANG KEMUNGKINAN</p><h2>Bagaimana kalau…</h2><p>Uji rencanamu, sebelum mengambil langkah.</p></div></div><div className="scenario-grid"><div className="scenario-controls"><details className="scenario-base" open={Number(income)===0}><summary>Angka dasar bulanan <span>Sesuaikan</span></summary><p>Awalnya memakai catatan bulan berjalan. Jika belum satu bulan penuh, isi estimasi bulananmu sendiri.</p><label>{biz?'Omzet':'Pemasukan'} (Rp)<input inputMode="numeric" value={income} onChange={e=>setIncome(e.target.value.replace(/\D/g,'').slice(0,12))}/></label><label>{biz?'Biaya operasional':'Pengeluaran'} (Rp)<input inputMode="numeric" value={expense} onChange={e=>setExpense(e.target.value.replace(/\D/g,'').slice(0,12))}/></label>{biz&&<label>HPP (Rp)<input inputMode="numeric" value={hpp} onChange={e=>setHpp(e.target.value.replace(/\D/g,'').slice(0,12))}/></label>}</details>
 <label className="scenario-slider"><span>{biz?'Perubahan omzet':'Perubahan pemasukan'}<b>{revenueChange>0?'+':''}{revenueChange}%</b></span><input aria-label="Perubahan pemasukan" type="range" min="-80" max="100" step="5" value={revenueChange} onChange={e=>setRevenue(Number(e.target.value))}/><small>{money(Number(income))} → {money(calc.nextIncome)}</small></label><label className="scenario-slider"><span>{biz?'Perubahan biaya':'Perubahan pengeluaran'}<b>{expenseChange>0?'+':''}{expenseChange}%</b></span><input aria-label="Perubahan pengeluaran" type="range" min="-80" max="100" step="5" value={expenseChange} onChange={e=>setExpenseChange(Number(e.target.value))}/><small>{money(Number(expense))} → {money(calc.nextExpense)}</small></label>
 {biz&&<label className="scenario-select">Asumsi HPP<select value={hppMode} onChange={e=>setHppMode(e.target.value as typeof hppMode)}><option value="ratio">Ikuti persentase omzet</option><option value="fixed">Nominal tetap</option></select></label>}<label className="scenario-select">Jangka waktu<select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value="1">1 bulan</option><option value="3">3 bulan</option><option value="6">6 bulan</option><option value="12">12 bulan</option></select></label><button className="text-action" onClick={()=>{setRevenue(0);setExpenseChange(0)}}><RotateCcw size={13}/> Reset perubahan</button></div>
 <div className="scenario-result"><span>Hasil simulasi · {biz?'laba bersih':'sisa arus kas'} / bulan</span><strong>{money(calc.net)}</strong><p className={calc.difference<0?'negative-text':'positive-text'}><ArrowUpRight size={14}/>{calc.difference>=0?'+':''}{money(calc.difference)} dari angka dasar</p><ResponsiveContainer width="100%" height={210}><AreaChart data={calc.series} margin={{top:15,left:-18,right:5,bottom:0}}><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{fontSize:10,fill:'var(--muted)'}}/><YAxis tickFormatter={shortMoney} tickLine={false} axisLine={false} tick={{fontSize:10,fill:'var(--muted)'}}/><Tooltip formatter={v=>money(Number(v))} contentStyle={{background:'var(--surface)',border:'1px solid var(--line)',borderRadius:10}}/><Area name="Angka dasar" dataKey="baseline" fill="transparent" stroke="#b6afb9" strokeDasharray="4 4" isAnimationActive={false}/><Area name="Skenario" dataKey="scenario" fill="#a08abb20" stroke="#a08abb" strokeWidth={2.5} isAnimationActive={false}/></AreaChart></ResponsiveContainer><div className="scenario-legend"><span><i/> Skenario</span><span><i/> Angka dasar</span></div><div className="scenario-foot">Saldo skenario pada bulan {months}<b>{money(calc.series.at(-1)!.scenario)}</b></div><small className="scenario-disclaimer">Simulasi dengan arus kas bulanan tetap. Tidak memperhitungkan transaksi baru, musim, atau perubahan lain. Tidak ada data keuangan yang diubah.</small></div></div></section>
}
