import {db,type Attachment,uid} from './db';
import {type Transaction,validAmount} from './finance';
export type UndoRecord={id:string;label:string;before?:Transaction;after?:Transaction;oldAttachment?:Attachment;expires:number};
export async function saveRecord(row:Transaction,file?:File,expectedRevision?:string):Promise<UndoRecord>{
 if(!validAmount(row.amount)||!row.description.trim())throw Error('Nominal dan deskripsi belum valid.');
 let before:Transaction|undefined,oldAttachment:Attachment|undefined;
 await db.transaction('rw',db.transactions,db.attachments,db.categories,async()=>{
 const cat=await db.categories.get(row.categoryId);if(!cat||cat.context!==row.context||cat.type!==row.type)throw Error('Kategori tidak sesuai konteks.');
 before=await db.transactions.get(row.id);if(expectedRevision&&before?.updatedAt!==expectedRevision)throw Error('Catatan berubah sejak dibuka. Tutup lalu buka kembali.');oldAttachment=before?.attachmentId?await db.attachments.get(before.attachmentId):undefined;
 if(file){if(!file.type.startsWith('image/')||file.size>5_000_000)throw Error('Bukti maksimal 5 MB.');row.attachmentId=uid();await db.attachments.put({id:row.attachmentId,mimeType:file.type,blob:file,createdAt:row.updatedAt,size:file.size});if(oldAttachment)await db.attachments.delete(oldAttachment.id)}await db.transactions.put(row);
 });return{id:uid(),label:before?'Perubahan transaksi':'Transaksi baru',before,after:row,oldAttachment,expires:Date.now()+15000};
}
export async function deleteRecord(row:Transaction):Promise<UndoRecord>{let oldAttachment:Attachment|undefined;await db.transaction('rw',db.transactions,db.attachments,async()=>{const live=await db.transactions.get(row.id);if(!live||live.updatedAt!==row.updatedAt)throw Error('Catatan berubah. Buka ulang sebelum menghapus.');if(live.attachmentId){oldAttachment=await db.attachments.get(live.attachmentId);await db.attachments.delete(live.attachmentId)}await db.transactions.delete(row.id)});return{id:uid(),label:'Transaksi dihapus',before:row,oldAttachment,expires:Date.now()+15000}}
export async function undoRecord(change:UndoRecord){if(Date.now()>change.expires)throw Error('Waktu urungkan sudah habis.');await db.transaction('rw',db.transactions,db.attachments,async()=>{const id=(change.after||change.before)!.id,live=await db.transactions.get(id);if(change.after?(!live||live.updatedAt!==change.after.updatedAt):!!live)throw Error('Catatan sudah berubah. Urungkan tidak diterapkan.');if(change.after?.attachmentId&&change.after.attachmentId!==change.before?.attachmentId)await db.attachments.delete(change.after.attachmentId);if(change.before){if(change.oldAttachment)await db.attachments.put(change.oldAttachment);await db.transactions.put(change.before)}else await db.transactions.delete(id)})}
export async function imageForAI(file:File){if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>8_000_000)throw Error('Pilih JPG, PNG, atau WebP maksimal 8 MB.');const bmp=await createImageBitmap(file);try{const scale=Math.min(1,1280/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);const c=canvas.getContext('2d');if(!c)throw Error('Gambar tidak dapat diproses.');c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(bmp,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.82).split(',')[1];if(data.length>1800000)throw Error('Gambar terlalu besar setelah dikompresi.');return {mimeType:'image/jpeg',data}}finally{bmp.close()}}
