import {chromium as pw} from 'playwright';
import assert from 'node:assert/strict';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';import fs from 'node:fs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
fs.mkdirSync(root+'/tmp/v4',{recursive:true});const passed=[];const pass=s=>{passed.push(s);console.log('PASS',s)};
const server=spawn(process.execPath,[root+'/node_modules/next/dist/bin/next','start','-H','0.0.0.0','-p','3000'],{cwd:root,stdio:['ignore','pipe','pipe']});let output='';server.stdout.on('data',d=>output+=d);server.stderr.on('data',d=>output+=d);let browser;
const errors=[];
try{
 for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:3000')).ok)break}catch{}await new Promise(r=>setTimeout(r,150));}
 browser=await pw.launch({executablePath:process.env.BROWSER_PATH||undefined,args:process.env.BROWSER_ARGS?JSON.parse(process.env.BROWSER_ARGS):['--no-sandbox','--disable-dev-shm-usage'],headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:960},timezoneId:'Asia/Jakarta'});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3000');await page.waitForSelector('.welcome-entry',{timeout:15000});await page.locator('.welcome-entry input').fill('Ari');await page.locator('.welcome-entry button').click();await page.waitForSelector('.world-hero');
 await page.evaluate(async()=>{const db=await new Promise((res,rej)=>{const r=indexedDB.open('finora-v1');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});const today=new Date(),iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,date=iso(today),month=date.slice(0,7),prev=iso(new Date(today.getFullYear(),today.getMonth()-1,Math.min(today.getDate(),25))),stamp=new Date().toISOString();const row=(id,c,t,n,cat,description,hpp=0,d=date)=>({id,context:c,type:t,amount:n,categoryId:`${c}-${t}-${cat}`,description,date:d,hppAmount:hpp,createdAt:stamp,updatedAt:stamp,sourceDestination:'DANA'});await new Promise((res,rej)=>{const t=db.transaction(['transactions','capitals','limits','goals','templates'],'readwrite');for(const rowdata of [row('p1','personal','income',7500000,'gaji','Gaji bulanan'),row('p2','personal','income',850000,'freelance','Proyek desain'),row('p3','personal','expense',875000,'tagihan','Tagihan bulanan'),row('p4','personal','expense',1200000,'belanja','Belanja kebutuhan'),row('p5','personal','expense',420000,'makan-minum','Makan & kopi'),row('p6','personal','expense',1400000,'belanja','Belanja bulan lalu',0,prev),row('b1','business','income',5400000,'penjualan','Penjualan produk digital',2880000),row('b2','business','expense',400000,'server','Layanan server')])t.objectStore('transactions').put(rowdata);t.objectStore('capitals').put({id:'c1',kind:'initial',amount:2000000,date,description:'Modal awal'});t.objectStore('limits').put({id:'l1',amount:3000000,warningThreshold:.8});t.objectStore('goals').put({id:month,month,revenueTarget:7000000,profitTarget:3500000});t.objectStore('templates').put({id:'q1',context:'personal',type:'expense',amount:25000,hppAmount:0,categoryId:'personal-expense-makan-minum',description:'Kopi sore',sourceDestination:'DANA',createdAt:stamp});t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close()});
 await page.reload();await page.waitForSelector('.world-hero');await page.waitForTimeout(900);await page.screenshot({path:root+'/tmp/v4/home-desktop.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('1440px Home tanpa overflow');
 await page.getByRole('button',{name:'Temui Elaina'}).first().click();await page.waitForSelector('.studio');await page.screenshot({path:root+'/tmp/v4/agent-desktop.png',fullPage:true});
 await page.getByRole('tab',{name:'Simulasi'}).click();await page.screenshot({path:root+'/tmp/v4/simulation-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.locator('.bottom-nav').getByRole('button',{name:'Home',exact:true}).click();await page.waitForTimeout(750);await page.screenshot({path:root+'/tmp/v4/home-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('390px Home tanpa overflow');
 await page.getByRole('button',{name:'Temui Elaina'}).first().click();await page.screenshot({path:root+'/tmp/v4/agent-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('390px Agent tanpa overflow');
 await page.setViewportSize({width:320,height:740});await page.getByRole('tab',{name:'Simulasi'}).click();await page.screenshot({path:root+'/tmp/v4/simulation-320.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('320px Simulasi tanpa overflow');

 // Read the isolated test browser's database; never touches a user's profile.
 const read=(table='transactions')=>page.evaluate(async(table)=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('finora-v1');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return await new Promise((resolve,reject)=>{const t=db.transaction(table);const r=t.objectStore(table).getAll();r.onsuccess=()=>{resolve(r.result);db.close()};r.onerror=()=>reject(r.error)})},table);
 const home=()=>page.locator('.bottom-nav').getByRole('button',{name:'Home',exact:true}).click();
 const agent=()=>page.locator('.bottom-nav').getByRole('button',{name:'Agent',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await home();
 await page.getByRole('button',{name:'Sapa Elaina',exact:true}).click();assert.ok(await page.locator('.elaina-greeting').isVisible());pass('Elaina dapat disapa');
 const before=(await read()).length;
 await page.locator('.hero-record').click();await page.locator('.amount-input input').fill('27000');await page.getByRole('textbox',{name:'Deskripsi',exact:true}).fill('Teh sore QA');await page.getByRole('checkbox',{name:/Simpan juga sebagai pintasan/}).check();await page.locator('.form-footer .primary').click();await page.waitForSelector('.undo-toast');assert.equal((await read()).length,before+1);await page.getByRole('button',{name:'Urungkan',exact:true}).click();assert.equal((await read()).length,before);assert.ok((await read('templates')).some(t=>t.description==='Teh sore QA'));pass('Simpan + favorit + urungkan transaksi baru');
 await page.getByRole('button',{name:/Teh sore QA/}).click();await page.waitForSelector('.record-form');assert.equal(await page.getByRole('textbox',{name:'Deskripsi',exact:true}).inputValue(),'Teh sore QA');assert.equal(await page.locator('.amount-input input').inputValue(),'27.000');await page.locator('.form-footer .primary').click();await page.waitForSelector('.undo-toast');await page.getByRole('button',{name:/Teh sore QA/}).first().click();await page.waitForSelector('.duplicate-notice');assert.ok(await page.locator('.form-footer .primary').isDisabled());await page.getByRole('checkbox',{name:'Ya, tetap simpan transaksi ini'}).check();assert.ok(await page.locator('.form-footer .primary').isEnabled());await page.getByRole('button',{name:'Batal',exact:true}).click();assert.equal((await read()).length,before+1);pass('Pintasan mengisi draf; duplikat meminta persetujuan');
 await page.locator('.bottom-nav').getByRole('button',{name:'Transaksi',exact:true}).click();await page.getByRole('button',{name:'Hapus Teh sore QA',exact:true}).click();await page.getByRole('dialog',{name:'Hapus transaksi'}).getByRole('button',{name:'Hapus transaksi',exact:true}).click();await page.waitForSelector('.undo-toast');assert.equal((await read()).length,before);await page.getByRole('button',{name:'Urungkan',exact:true}).click();assert.equal((await read()).length,before+1);pass('Hapus dan urungkan mengembalikan catatan');
 await agent();await page.getByRole('tab',{name:'Obrolan',exact:true}).click();const ask=async text=>{await page.locator('#agent-composer').fill(text);await page.getByRole('button',{name:'Kirim pesan',exact:true}).click()};
 await ask('Catat beli makan 25 ribu');await page.waitForSelector('.plan-card');assert.equal((await read()).length,before+1);await page.getByRole('button',{name:'Batalkan',exact:true}).click();assert.equal((await read()).length,before+1);await ask('Catat beli makan 25 ribu');await page.waitForSelector('.plan-card');await page.getByRole('button',{name:'Konfirmasi & simpan',exact:true}).click();await page.waitForSelector('.plan-card',{state:'detached'});assert.equal((await read()).length,before+2);pass('Agent menyiapkan, membatalkan, dan menyimpan hanya setelah konfirmasi');
 await ask('Ringkas bulan ini');await page.waitForSelector('.evidence-button');await page.locator('.evidence-button').last().click();await page.waitForSelector('.evidence-sheet');assert.ok(await page.locator('.evidence-list .activity-row').count()>0);await page.getByRole('dialog',{name:'Catatan sumber'}).getByRole('button',{name:'Tutup',exact:true}).click();pass('Jawaban Agent memiliki catatan sumber yang dapat dibuka');
 await page.getByRole('tab',{name:'Memori',exact:true}).click();await page.getByRole('textbox',{name:'Preferensi baru'}).fill('Gunakan jawaban ringkas.');await page.getByRole('button',{name:'Simpan memori',exact:true}).click();await page.waitForSelector('.memory-list article');assert.equal((await read('memories')).length,1);await page.getByRole('button',{name:'Ubah',exact:true}).click();await page.getByRole('textbox',{name:'Ubah memori'}).fill('Gunakan jawaban ringkas dan hangat.');await page.getByRole('button',{name:'Simpan memori',exact:true}).click();assert.equal((await read('memories'))[0].text,'Gunakan jawaban ringkas dan hangat.');pass('Memori dapat dibuat dan diubah');
 const dataBeforeSimulation=JSON.stringify(await read());await page.getByRole('tab',{name:'Simulasi',exact:true}).click();const oldResult=await page.locator('.scenario-result>strong').innerText();await page.getByRole('slider',{name:'Perubahan pemasukan',exact:true}).focus();await page.keyboard.press('ArrowRight');assert.notEqual(await page.locator('.scenario-result>strong').innerText(),oldResult);assert.equal(JSON.stringify(await read()),dataBeforeSimulation);pass('Simulasi interaktif tidak menulis catatan');
 await page.locator('.context-row').getByRole('button',{name:'Bisnis',exact:true}).click();await page.getByRole('tab',{name:'Memori',exact:true}).click();assert.equal(await page.locator('.memory-list article').count(),0);await page.getByRole('tab',{name:'Obrolan',exact:true}).click();assert.equal(await page.locator('.studio-message').count(),0);await ask('Ringkas bulan ini');await page.waitForSelector('.studio-message.agent');assert.ok((await page.locator('.studio-message.agent').innerText()).includes('HPP'));pass('Obrolan, memori, dan perhitungan terpisah per konteks');
 await page.locator('.context-row').getByRole('button',{name:'Pribadi',exact:true}).click();await page.getByRole('tab',{name:'Memori',exact:true}).click();await page.getByRole('button',{name:/Hapus memori Gunakan jawaban/}).click();assert.equal((await read('memories')).length,0);pass('Memori dapat dihapus');
 // Mocked upstream AI: verifies orchestration/UI, does not consume Gemini quota.
 let requests=[];await page.route('**/api/agent',async route=>{const request=route.request().postDataJSON();requests.push(request);let result;if(request.mode==='receipt'){assert.ok(request.image.data.length<1800000);assert.equal(request.image.mimeType,'image/jpeg');result={reply:'Periksa kembali draf.',receipt:{amount:98000,description:'Bukti QA',date:new Date().toLocaleDateString('sv-SE'),type:'expense',categoryId:'personal-expense-tagihan',sourceDestination:'DANA',confidence:'medium'}}}else if(!request.finalPass){result={reply:'Membaca catatan kopi.',actions:[],tools:[{name:'search',query:'kopi',from:'1900-01-01',to:'9999-12-31'}]}}else{assert.ok(request.toolResults[0].result.records.length);assert.ok(request.toolResults[0].result.records.every(r=>r.context==='personal'));result={reply:'Pengeluaran kopi ditemukan dalam catatan sumber berikut.',actions:[],tools:[]}}await route.fulfill({json:result})});
 await page.evaluate(()=>localStorage.setItem('finora-gemini-key','test-only-mock-key'));await page.reload();await page.waitForSelector('.world-hero');await page.locator('.hero-record').click();await page.locator('.attachment-field input').setInputFiles(root+'/public/art/elaina-avatar.webp');assert.equal(requests.length,0);await page.getByRole('button',{name:'Baca dengan Gemini',exact:true}).click();await page.waitForSelector('.receipt-note');assert.equal(await page.locator('.amount-input input').inputValue(),'98.000');assert.equal((await read()).length,before+2);await page.screenshot({path:root+'/tmp/v4/receipt-draft-mobile.png',fullPage:true});await page.getByRole('button',{name:'Batal',exact:true}).click();pass('OCR terkompresi dipanggil eksplisit; hasil hanya draf (mock)');
 await agent();await page.getByRole('tab',{name:'Obrolan',exact:true}).click();await ask('Tolong telusuri transaksi kopi dan jelaskan');await page.waitForFunction(()=>document.querySelector('.studio-messages')?.textContent?.includes('Pengeluaran kopi ditemukan'));assert.equal(requests.length,3);assert.equal(requests[1].finalPass,undefined);assert.equal(requests[2].finalPass,true);assert.equal((await read()).length,before+2);pass('Agent menjalankan alat baca dan menyusun jawaban dalam maksimal dua panggilan (mock)');
 await page.getByRole('button',{name:'Suasana Finora',exact:true}).click();await page.getByRole('combobox',{name:'Intensitas animasi'}).selectOption('reduced');await page.getByRole('dialog',{name:'Suasana Finora'}).getByRole('button',{name:'Tutup',exact:true}).click();await home();assert.equal(await page.locator('.companion-breath').evaluate(e=>getComputedStyle(e).animationName),'none');pass('Mode hemat gerak menghentikan animasi');
 await page.evaluate(()=>localStorage.removeItem('finora-gemini-key'));await context.setOffline(true);await page.reload();await page.waitForSelector('.world-hero',{timeout:15000});await page.waitForTimeout(800);assert.equal((await read()).length,before+2);await agent();await page.getByRole('tab',{name:'Obrolan',exact:true}).click();await ask('Saldo saya berapa');await page.waitForFunction(()=>document.querySelector('.studio-messages')?.textContent?.includes('Aku bisa merangkum')||document.querySelector('.studio-messages')?.textContent?.includes('Saldo pribadimu'));pass('Reload offline dan Agent lokal berfungsi');await context.setOffline(false);
 assert.deepEqual(errors,[]);pass('Tidak ada runtime page error');
 const portable=await browser.newPage({viewport:{width:390,height:844}});await portable.goto('file://'+path.resolve(root,'../Finora_Preview.html'));await portable.waitForSelector('.welcome-entry');await portable.locator('.welcome-entry input').fill('Teman');await portable.locator('.welcome-entry button').click();await portable.waitForSelector('.world-hero');await portable.locator('.preview-tools summary').click();await portable.locator('#demo-data').click();await portable.waitForSelector('.world-hero');await portable.waitForFunction(()=>document.querySelector('.world-number')?.textContent?.includes('5.855.000'),{timeout:15000});assert.equal(await portable.locator('.companion-body').evaluate(e=>e.complete&&e.naturalWidth>0),true);await portable.locator('.bottom-nav').getByRole('button',{name:'Agent',exact:true}).click();await portable.getByRole('tab',{name:'Simulasi',exact:true}).click();assert.ok(await portable.locator('.scenario-result').isVisible());pass('HTML portable: onboarding, data contoh, gambar, Agent lokal, simulasi');
 fs.writeFileSync(root+'/tmp/v4/browser-results.json',JSON.stringify({checkedAt:new Date().toISOString(),passed,pageErrors:errors,geminiLive:false},null,2));
 await browser.close();
}catch(e){console.error(e);console.log(output);process.exitCode=1}finally{if(browser)await browser.close().catch(()=>{});server.kill()}
