import {build} from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const assets={};for(const file of fs.readdirSync(path.join(root,'public/art')))assets['/art/'+file]='data:image/webp;base64,'+fs.readFileSync(path.join(root,'public/art',file)).toString('base64');
const result=await build({entryPoints:[path.join(root,'scripts/preview-entry.tsx')],bundle:true,write:false,minify:true,format:'iife',platform:'browser',jsx:'automatic',tsconfig:path.join(root,'tsconfig.json'),define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'portable-isolation',setup(b){b.onLoad({filter:/\.(tsx|ts)$/},args=>{if(args.path.includes('node_modules'))return;let contents=fs.readFileSync(args.path,'utf8');contents=contents.replace(/finora-v1/g,'finora-preview-v4').replace(/finora-name/g,'finora-preview-name').replace(/finora-context/g,'finora-preview-context').replace(/finora-theme/g,'finora-preview-theme').replace(/finora-preferences/g,'finora-preview-preferences').replace(/finora-last-agent-/g,'finora-preview-last-agent-').replace(/finora-gemini-key/g,'finora-preview-key').replace(/finora-gemini-model/g,'finora-preview-model');contents=contents.replace("if('serviceWorker'in navigator&&location.protocol!=='file:')","if(false)");return{contents,loader:args.path.endsWith('.tsx')?'tsx':'ts'}})}}]});
// One copy of each bitmap in JS. All component instances share these data URLs.
let js=result.outputFiles[0].text;for(const key of Object.keys(assets))js=js.split(JSON.stringify(key)).join('window.__FINORA_ART['+JSON.stringify(key)+']');
let css=['globals','celestial','living'].map(name=>fs.readFileSync(path.join(root,'app',name+'.css'),'utf8')).join('\n').replace("@import 'tailwindcss';",'');
for(const [key,value]of Object.entries(assets))css=css.split(key).join(value);css=css.replace('/fonts/inter-latin-variable.woff2','data:font/woff2;base64,'+fs.readFileSync(path.join(root,'public/fonts/inter-latin-variable.woff2')).toString('base64'));
css='*,::before,::after{box-sizing:border-box}button,input,select,textarea{font:inherit}button{border-style:solid}h1,h2,h3,p{margin:0}img,svg{vertical-align:middle}img{max-width:100%}button{cursor:pointer}\n'+css;
const html=`<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Finora IV · Preview interaktif</title><style>${css}\n.preview-tools{position:fixed;z-index:110;right:10px;top:5px;font:9px system-ui;color:#e0d4e9;background:#241f30ed;padding:4px 7px;border:1px solid #bba4c94a;border-radius:6px}.preview-tools summary{cursor:pointer}.preview-tools button{display:block;color:#eee1f6;background:#655277;border:0;border-radius:4px;padding:8px;margin:6px 0}.preview-tools p{max-width:220px;line-height:1.6}</style></head><body><details class="preview-tools"><summary>PREVIEW · LOKAL</summary><p>Jelajahi Elaina, transaksi, Agent lokal, dan simulasi. Gemini/OCR membutuhkan source Next.js. Data contoh dimuat hanya setelah tombol ditekan.</p><button id="demo-data">Isi data contoh</button></details><div id="root"></div><script>window.__FINORA_ART=${JSON.stringify(assets)};${js.replace(/<\/script/gi,'<\\/script')}</script></body></html>`;
const out=process.argv[2]||path.resolve(root,'../Finora_Preview.html');fs.writeFileSync(out,html);console.log(out,Math.round(Buffer.byteLength(html)/1024)+' KB');
